# Generated by Django 3.1.1 on 2020-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_list', models.CharField(blank=True, max_length=10000, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
