# Generated by Django 3.1.1 on 2020-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was_rest', '0002_stream_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream_1',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
